add lv_obj_set_user_data function
kisvegabor/lvgl pull request #1019
Opened 2019-04-14 05:44 UTC by canardos

The new v6.0 `user_data` mechanism includes a `lv_obj_get_user_data` function, but the set data function was missing.

I'm not sure if this is an oversight, or if the user is expected to set the data directly via the object pointer. I presume the former, since the get function was implemented and the other `lv_obj_t` members have set/get function pairs.

2019-04-14 12:56 UTC, embeddedt requested changes
This needs to handle `USE_USER_DATA_MULTI` as well.

2019-04-14 13:57 UTC, kisvegabor commented
@canardos 
I left it intentionally because now `lv_obj_user_data_t`  can be e.g.:
- `typedef uint8_t lv_obj_user_data_t`;
- `typedef void * lv_obj_user_data_t`;
- `typdef struct{ .... } lv_obj_user_data_t;` with many elemnts

These are very different data types and I couldn't imagine a function prototype which is suitable for all possible types. Your current version can be problematic if, for any reason, a larger struct needs to be passed.

As I' thinking about it again `void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t * data)` could work with a memcpy inside the function.

@embeddedt 
Do we really need to support `USE_USER_DATA_MULTI`? It's not really for the user, but for bindings and other "background' things. What do you think?

2019-04-14 15:11 UTC, canardos commented
@kisvegabor `lv_obj_user_data_t` is user defined. It's currently a `void*`, but as you stated the user is free to change it to whatever type they see fit. Presumably the most common use case will be a pointer to some multi-member `struct`.

Am I right that your concern is that a user will choose to store a large struct directly (rather than ptr) in the lv obj., and then set it via this function resulting in a copy via the stack? In that situation, I'm not sure copying via `memcpy` will be much more efficient, but it does have the benefit of avoiding the potential of running out of stack space, if someone decided it was a good idea to store a massive object in this way.

I don't have a strong opinion either way, passing by value or by reference and then copying, but I do think that a function is required.

Regarding @embeddedt 's comment, I'm not clear what the event/signal/design user data is intended for, but I can't imagine that a single set function is going to be shared between them and this, so not sure on the relevance. Perhaps by "This" you meant this commit and not this function?

2019-04-14 21:40 UTC, embeddedt commented
@canardos I was referring to the PR as a whole, not just one function. Sorry for the confusion.

@kisvegabor We could ignore `USE_USER_DATA_MULTI`.

The problem with the API that you suggested is that it seems confusing. Someone using a basic `void *` pointer for `lv_obj_user_data_t` could easily get confused and pass its value instead of its address.

2019-04-15 12:12 UTC, canardos commented
@embeddedt Got it, thanks.

@kisvegabor Apologies if this has been discussed before, but what's the rationale for including the `lv_obj_user_data_t` type directly into the object rather than a pointer to it (as was the case previously with the untyped free ptr)?

I guess it's to free the user from having to allocate/free the memory themselves? I have custom data for a few objects, but the types differ in different places, so I end up having to use a `void *` and cast anyway. Is it a common use case that requires storing a single data type and allocating it for every lv object used?

I tend to agree with @embeddedt that the potential for errors goes up when requiring a reference to the reference, but I'm not sure there's any alternative if the user data is being stored directly in the lv object. I think it's probably the least bad option at this point :)

For discussion, below is a summary of the alternatives mentioned. None really feel great unless storing a reference. Please add/remove as appropriate.

```
/* Option 1 - store reference, easy to get/set, but user must
   allocate/free if storing anything larger than a pointer */

lv_obj_user_data_t * user_data;

/* Get ref */
lv_obj_user_data_t * lv_obj_get_user_data(lv_obj_t * obj);
/* Set ref */
void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t * data);

/* Option 2 - store value, expensive to set, framework handles allocation/free */

lv_obj_user_data_t user_data;
/* Get ref */
lv_obj_user_data_t * lv_obj_get_user_data_ref(lv_obj_t * obj);

/* Set via ref and copy */
void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t * data_ref);

/* Set via value */
void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t data);

/* Both */
void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t * data);
void lv_obj_set_user_data_direct(lv_obj_t * obj, lv_obj_user_data_t data);

/* Dual direction copy */
enum direction_t { IN, OUT };
void lv_obj_copy_user_data(lv_obj_t * obj, lv_obj_user_data_t * data, direction_t direction);
```

2019-04-15 13:10 UTC, embeddedt commented
> ```c
>
>/* Option 2 - store value, expensive to set, framework handles allocation/free */
>
>lv_obj_user_data_t user_data;
>/* Get ref */
>lv_obj_user_data_t * lv_obj_get_user_data_ref(lv_obj_t * obj);
>```

I don't see what's "expensive" about this method. The user doesn't have to set all the fields of the structure at once; they can set them one at a time.

Personally I think this is the cleanest.

2019-04-15 14:35 UTC, kisvegabor commented
> Apologies if this has been discussed before, but what's the rationale for including the lv_obj_user_data_t type directly into the object rather than a pointer to it (as was the case previously with the untyped free ptr)?
> I guess it's to free the user from having to allocate/free the memory themselves? I have custom data for a few objects, but the types differ in different places, so I end up having to use a void * and cast anyway. Is it a common use case that requires storing a single data type and allocating it for every lv object used?

Yes, it's to "free the user from having to allocate/free the memory themselves". What about using a `union` and a "type" field to store different type of data for objects?
 

 
>```c
>/* Set via ref and copy */
>void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t * data_ref);
>```

It has big overhead in usability for simply user data types (`uint8_t` or `void *`):
```c
typedef uint8_t  lv_obj_user_data_t;
lv_obj_user_data_t x = 3;
lv_obj_set_user_data(obj, &x);
```
```c
typedef void *  lv_obj_user_data_t;
lv_obj_user_data_t p = a_function_pointer;
lv_obj_set_user_data(obj, &p); 
/*It's not working becaue not the data pointed by `a_function_pointer` 
need to be copied but `a_function_pointer` itself*/
lv_obj_set_user_data(obj, a_function_pointer); 
```

I imagined the following use with only a `get` function:

```c
lv_obj_user_data_t * user_data;

/* Get ref */
lv_obj_user_data_t * p = lv_obj_get_user_data(obj);
/* Set ref */
p->something = x;
```

As @canardos said that my intention was to avoid passing large struct parameters (which are passed via the stack). However, having a user_data with ~1000 byte size is not a real-life scenario.  To copy 20-30 bytes via stack is still acceptable IMO.

So it also can work:
```c
/* Set via value */
void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t data);
```

It even allows setting an integer if the user data is only `uint8_t`:
```c
lv_obj_set_user_data(obj, 3);   /*uint8_t*/
lv_obj_set_user_data(obj, a_function_pointer);  /*void * */

void lv_obj_set_user_data(lv_obj_t * obj, lv_obj_user_data_t data)
{
   memcpy(obj->user_data, &user_data, sizeof(lv_obj_user_data_t));
}
```
What do you think about it?

2019-04-15 16:36 UTC, canardos commented
> I don't see what's "expensive" about this method.

Sorry I didn't make it very clear from the code comments. Option 2 meant stored by value and using one of the set_data functions listed below it, not the get_data function only. The set_data function is the expensive part, since it requires a full copy vs if the custom data was only stored as a reference (option 1).

In cases where `lv_obj_user_data_t` is a struct or equivalent, then having a `lv_obj_get_user_data` function (returning a reference) only is fine. For cases where `lv_obj_user_data_t` is a basic data type or pointer, it means

```
*lv_obj_get_user_data(obj) = new_value;
```
instead of
```
lv_obj_set_user_data(obj, new_value);
```

which is okay, but not great in terms of code readability/intuitiveness.

@kisvegabor Understand and agree with all of your examples. I think the pass by value set function (your final example) is fine. It's what's implemented in this PR, although the PR uses direct assignment rather than calling `memcpy` as it's likely to give the compiler greater flexibility to optimize depending on what's being passed. In most cases the compiler will just generate the call to `memcpy`, but there are some scenarios where more optimal output might be possible.

Alternatively, understand if you think having a get function only and no set function is best. There's really no perfect solution here.

2019-04-16 04:44 UTC, kisvegabor commented
@canardos Once we discussed `memcpy` vs "assignment" and concluded that `memcpy` is preferred. 
It seems finally you also vote for it.  

All these are being said, I think there is no disadvantage of having a `set` function like this one in the PR.

So from my side, the only thing is to change the assignment to `memcpy`. @embeddedt?

2019-04-16 12:49 UTC, embeddedt commented
@kisvegabor Agreed; everything else is fine.

2019-04-19 03:21 UTC, kisvegabor commented
Merged, thank you!

2019-04-19 03:21 UTC, merged