Initial addition of asynchronous callbacks
kisvegabor/lvgl pull request #1137
Opened 2019-07-05 18:47 UTC by embeddedt

2019-07-06 10:01 UTC, kisvegabor requested changes
Thank you! Looks great in general. I have only a few simple remarks.

2019-07-06 10:06 UTC, kisvegabor commented
Although it's a new feauture I think we merge it to `master` because it's required to conveniently use e.g. `LV_EVENT_DELETE`.
What do you think?

2019-07-06 10:55 UTC, embeddedt commented on src/lv_misc/lv_async.h
> +void lv_obj_del_async(struct _lv_obj_t *obj);
@kisvegabor Yes, sorry for the mix-up.

2019-07-06 10:56 UTC, embeddedt commented
@kisvegabor That's fine.

I will make the remaining changes later today.

2019-07-06 14:29 UTC, kisvegabor commented
> It will have to be merged manually, though, or I will have to find some way of rebasing my commits.

Why can't we simply merge it as usual?

2019-07-06 14:35 UTC, embeddedt commented
I created the `async` branch based on `dev-6.1`.

2019-07-06 15:02 UTC, kisvegabor commented
I see. I downloaded the patch from [here](https://github.com/littlevgl/lvgl/pull/1137.patch) and I could apply it to master (there were only some white space error.)

![image](https://user-images.githubusercontent.com/7599318/60757812-c44f5d80-a00f-11e9-8d20-3da28009817a.png)

2019-07-06 18:00 UTC, embeddedt commented
@kisvegabor In order for that to work, I have to change the base branch back to `dev-6.1` (which I just did). Otherwise it will still apply all of the previous commits.

2019-07-06 19:50 UTC, embeddedt commented
I moved `lv_obj_del_async` and cherry-picked the changes to master.

2019-07-06 19:50 UTC, closed without merging

2019-07-07 15:39 UTC, kisvegabor commented
Great, thank you!
I've updated the docs: https://docs.littlevgl.com/en/html/overview/task.html#asynchronous-calls

2019-07-07 15:41 UTC, embeddedt commented
> I've updated the docs

I like the description of the feature but the example seems to be a bit misleading. When you use `delay` in the `led_flash` function it makes it look like it's running on a parallel thread, when in reality it's going to block all execution.

2019-07-07 15:54 UTC, kisvegabor commented
Ture. Do you have good and simple example idea?

2019-07-08 04:10 UTC, kisvegabor commented
I've got an idea: we can a `delay` parameter too to `lv_async_call` and return the created `lv_task_t` this way it can be used for a timeout too or can be deleted if the expected event happened. What do you think?

2019-07-08 16:36 UTC, embeddedt commented
> Do you have good and simple example idea?

Deleting an object's parent is pretty straightforward.

> What do you think?

Well... at that point it would basically be a wrapper around `lv_task_create` that calls `lv_task_once`, right? I think for more advanced cases we should encourage people to use `lv_task_create` directly.

2019-07-08 18:22 UTC, kisvegabor commented
> Deleting an object's parent is pretty straightforward.

I've updated the example: https://docs.littlevgl.com/en/html/overview/task.html#asynchronous-calls

> Well... at that point it would basically be a wrapper around lv_task_create that calls lv_task_once, right? I think for more advanced cases we should encourage people to use lv_task_create directly.

Alright. It's better to not change the API after the release anyway. :smile: