widget tableview: add new function lv_tabview_set_tab_name() to change a tab name during runtime
kisvegabor/lvgl pull request #1653
Opened 2020-07-12 10:07 UTC by mibcat

Hi !
I have a similar [use case](https://forum.lvgl.io/t/how-to-change-the-tab-name-in-a-tabview-and-update-the-screen-with-the-new-name/1254) and want to update the tab name dynamically during runtime.
But looking into `lv_tabview.c` code I realized that this could not be just a one-liner :smile: 

Because I'm not very familiar with the **lvgl** framework in detail there might be room for improvements ...

2020-07-12 11:39 UTC, embeddedt requested changes

2020-07-12 11:39 UTC, embeddedt commented on src/lv_widgets/lv_tabview.c
> +  // get tabview's ext pointer which contains the tab name pointer list
C-style comments, please. `/* */` :slightly_smiling_face:

2020-07-12 12:27 UTC, mibcat commented on src/lv_widgets/lv_tabview.c
> +  // get tabview's ext pointer which contains the tab name pointer list
done

2020-07-12 12:28 UTC, embeddedt approved these changes

2020-07-13 09:09 UTC, kisvegabor commented
Looks good. Please add a few lines about it in the docs.
See: https://docs.lvgl.io/latest/en/html/contributing/index.html#improve-the-docs

2020-07-13 17:03 UTC, mibcat commented
Cloning the lvgl/docs repo from my fork and switching to dev branch gives me the following (so far unseen) error message:
```bash
> git checkout dev
fatal: 'dev' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
```

But I can't see anything unusual:
```bash
> git remote show origin 
* remote origin
  Fetch URL: git@github.com:mibcat/docs.git
  Push  URL: git@github.com:mibcat/docs.git
  HEAD branch: master
  Remote branches:
    dev        tracked
    latest     tracked
    master     tracked
    release/v6 tracked
    release/v7 tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

therefore I worked on with:
`git checkout origin/dev` followed by a `git checkout dev` again

Hope this had no negative effects ... PR is on the way

2020-07-13 17:36 UTC, kisvegabor commented
It's because dev is also a directory.

`git checkout dev --` should work.

2020-07-13 17:42 UTC, kisvegabor commented
I merged the PR, thank you.

One last thing: please add a line to CHANGELOG.md.

2020-07-13 17:57 UTC, kisvegabor commented
Great! Thank you very much! :slightly_smiling_face:

2020-07-13 17:57 UTC, merged

2020-07-13 17:58 UTC, mibcat commented
added to V7.2.0 - hope this was the correct location (because branch dev is mentioned in V7.3.0)

2020-07-13 18:00 UTC, kisvegabor commented
Ups, v7.2 is in `master` and `v7.3` in `dev`. So it should be under `v7.3`. I've updated it here: https://github.com/lvgl/lvgl/commit/7e38ac68e3e2a84fabbb70b5462ba2b78b01284f

2020-07-13 18:51 UTC, mibcat commented
Ok - thanks for correction.