fix encoded letter bug
kisvegabor/lvgl pull request #2252
Opened 2021-05-11 14:34 UTC by guoweilkd

### Description of the feature or fix

When roller widget scrolls to the last option and clicks on it, a heap-buff-overflow fatal error occurs.below is a screenshot of the error.
![txt_error](https://user-images.githubusercontent.com/35251456/117833335-d56ef280-b2a8-11eb-8de1-b03c622fbce1.png)

The code snippet that causes the error reasion is:
```
uint32_t letter      = _lv_txt_encoded_next(bidi_txt, &i);
uint32_t letter_next = _lv_txt_encoded_next(&bidi_txt[i], NULL);
```
if `letter` return `\0`.then `&bidi_txt[i]` will be a wild pointer. fix code is:
```c
*letter_next = *letter != '\0' ? _lv_txt_encoded_next(&txt[*ofs], NULL)
```

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update the documentation
- [ ] Update CHANGELOG.md

2021-05-11 20:16 UTC, embeddedt requested changes
The implementation looks good; I like the idea of moving this check into a common function. 

One thing: please review the shadowing error and fix it.

2021-05-12 12:54 UTC, embeddedt approved these changes

2021-05-15 13:29 UTC, embeddedt commented
@kisvegabor Can we merge this?

2021-05-19 11:27 UTC, kisvegabor commented
Sorry for the late reply.

Looks good to me too. Let's merge!

2021-05-19 11:27 UTC, merged