Added printf-like function attribute to _lv_txt_set_text_vfmt and lv_label_set_text_fmt
kisvegabor/lvgl pull request #2332
Opened 2021-06-24 23:39 UTC by Avamander

### Description of the feature or fix

Added printf-like function attribute to _lv_txt_set_text_vfmt and lv_label_set_text_fmt. This improves static analysis and compiler warnings of incorrect format usage.

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md) - No functional difference 
- [ ] Update the documentation - No functional difference

2021-06-25 03:22 UTC, embeddedt requested changes
Since this is a compiler-specific attribute, please move this into a macro which is defined to this when GCC or Clang is being used, and just blank otherwise.

2021-06-25 09:30 UTC, Avamander commented
@embeddedt Hopefully the latest commit implements it as requested.

2021-06-25 14:53 UTC, embeddedt commented
I think it would be better to have it in a common header file which both of the other headers include, but I'm not sure what the right spot to put it is.

@kisvegabor Do you have any ideas?

2021-06-28 10:04 UTC, kisvegabor commented
> I think it would be better to have it in a common header file which both of the other headers include, but I'm not sure what the right spot to put it is.

[lv_types.h](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_types.h) can be a good candidate.

2021-07-11 19:19 UTC, merged

2021-07-11 19:20 UTC, embeddedt commented
I've merged this with the attribute moved to `lv_types.h`. Thanks for the contribution!

2021-07-11 19:23 UTC, Avamander commented
@embeddedt 

> I've merged this with the attribute moved to `lv_types.h`. Thanks for the contribution!

Thank you a lot for finding the time to do it!

2022-02-04 13:52 UTC, Satnet commented
Did this fix the issue where floats only shows "f" as output?
I just tested in 8.1.

```
    lv_obj_t * test lv_label_create(screen);
    lv_label_set_text_fmt(test, "Value: %d", 15); // Shows "Value: 15"
    lv_label_set_text_fmt(test, "Value: %f", 15.0); // Shows "f"
```

2022-02-04 14:17 UTC, embeddedt commented
For floating-point to work be sure to enable [`LV_SPRINTF_USE_FLOAT`](https://github.com/lvgl/lvgl/blob/2c7760c6875dce510133c7c6788dc447cb8c2d5b/lv_conf_template.h#L268) in `lv_conf.h`.

2022-02-04 14:19 UTC, Satnet commented
> For floating-point to work be sure to enable [`LV_SPRINTF_USE_FLOAT`](https://github.com/lvgl/lvgl/blob/2c7760c6875dce510133c7c6788dc447cb8c2d5b/lv_conf_template.h#L268) in `lv_conf.h`.

Thanks for being quick with a good reply. And for making me feel dumb hahaha.