fix some errors in  bidi algorithm when displaying arabic
kisvegabor/lvgl pull request #2777
Opened 2021-11-08 10:21 UTC by Bluelongshirt

fix the bug [https://github.com/lvgl/lvgl/issues/2712](url).

2021-11-09 12:40 UTC, kisvegabor requested changes
Thank you! Looks good in general, but please fix some formatting issues.

2021-11-09 12:40 UTC, kisvegabor commented on src/misc/lv_bidi.c
> +
Please remove these extra empty lines.

2021-11-09 12:40 UTC, kisvegabor commented on src/misc/lv_bidi.c
> +         if(dir==LV_BASE_DIR_LTR || dir==LV_BASE_DIR_RTL)
Please remove the extra spaces from here.

2021-11-10 01:52 UTC, Bluelongshirt commented
I am sorry that there is a problem with the format of the file, I fixed the problem, you see if it is correct

2021-11-10 09:47 UTC, kisvegabor commented
Looks good, thank you!

2021-11-10 09:47 UTC, merged