fix(png):failed to compile using arm-none-eabi-gcc
kisvegabor/lvgl pull request #3317
Opened 2022-05-02 15:04 UTC by lihuanhuan

### Description of the feature or fix

in arm-none-eabi-gcc ,uint32_t is defined to long unsigned int,it saying "expected 'unsigned int *' but argument is of type 'uint32_t *' {aka 'long unsigned int *'}"

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

2022-05-02 15:48 UTC, embeddedt requested changes, later dismissed
Changing to `unsigned` is not safe as it doesn't specify the exact size of the integer like `uint32_t` does.

Which function expects `unsigned int *`? That should possibly be changed to accept `uint32_t *` instead.

2022-05-04 10:28 UTC, lihuanhuan commented
In the lodepng,all unsigned is considered as long unsigned int in arm-none-eabi-gcc
example:
unsigned lodepng_decode32(unsigned char** out, unsigned* w, unsigned* h,const unsigned char* in, size_t insize);

2022-05-04 12:24 UTC, embeddedt commented
I see. It indeed appears that lodepng makes extensive use of this convention. I wasn't aware of that when I wrote my previous comment, sorry.

@kisvegabor/@xiaoxiang781216, what do you think we should do about this?

2022-05-04 14:12 UTC, xiaoxiang781216 commented
> I see. It indeed appears that lodepng makes extensive use of this convention. I wasn't aware of that when I wrote my previous comment, sorry.
> 
> @kisvegabor and/or @xiaoxiang781216, what do you think we should do about this?

either uint32_t or unsigned int is fine, but it's wrong to mix both since uint32_t may map to other type(e.g. unsigned long) on some platform.

2022-05-04 20:22 UTC, kisvegabor commented
`unsigned` without `int` seems really odd to me but it's standard. At least in `lv_png.c` we should use `unsigned int`.

IMO it's not a problem if it maps to different size on different platforms because any of the possible options provide enough room for the width and height of the image.

So suggest using `unsigned int`. :slightly_smiling_face:

2022-05-09 12:06 UTC, kisvegabor commented
Why is it closed?

2022-05-09 12:07 UTC, embeddedt commented
It must have been a GitHub issue. I never received a notification about anyone closing it.

2022-05-09 12:12 UTC, kisvegabor commented
Hm, strange. 

Anyway, are you ok with `unsigned int`?

2022-05-09 12:12 UTC, embeddedt commented
:+1:

2022-06-02 12:22 UTC, embeddedt commented
@lihuanhuan Can you please update this to use `unsigned int` instead of `unsigned` for convention reasons? Then this is ready to be merged.

2022-07-01 02:15 UTC, closed without merging