Avoid object defocusing in signle group object
kisvegabor/lvgl pull request #526
Opened 2018-11-05 12:19 UTC by AloyseTech

This PR allows single object group to keep focus on the object and stay in edit mode if applicable. 

For example, currently if a screen has only a list object, and this object is added to a newly created group, a long press with an encoder will get the list out of edit mode, which is not desirable. This PR solves this issue.

This is related to issue #499

2018-11-06 15:34 UTC, kisvegabor requested changes

2018-11-06 15:34 UTC, kisvegabor commented on lv_core/lv_indev.c
> +                if(focused) //  && (i->group->obj_ll.head != i->group->obj_ll.tail)
Remove the comment:
```suggestion
                if(focused)
```

2018-11-06 15:36 UTC, kisvegabor commented
Hi,

Thank you for the PR!
I checked it and it looks well! I've just added a change request to remove the comment. I tried this feature of GitHub first time, so sorry, if made it wrong.

2018-11-06 15:43 UTC, AloyseTech commented
I applied your change request. This GitHub feature is nice!

2018-11-06 16:00 UTC, kisvegabor approved these changes

2018-11-06 16:01 UTC, merged

2018-11-06 16:01 UTC, kisvegabor commented
Great!
Thank you! :)

2018-11-09 06:15 UTC, kisvegabor commented
Hi,

I've just realized that the object can't go to edit mode automatically because it's possible that indev not supports edit mode (like a keypad).
Everything else remained, but you need to go to edit mode manually.

See: https://github.com/littlevgl/lvgl/commit/d643219ee8d9df5273656840033ff011fc588490