feat(image, layer): add bitmap mask feature
kisvegabor/lvgl pull request #5545
Opened 2024-01-31 19:21 UTC by kisvegabor

### Description of the feature or fix

Allow using an A8 bitmap mask for 
- the image widget
- as a style property in which case a layer will be created and that layer will be masked 

Current limitations
- In SW render transformation and mask doesn't work together
- In SW render only RGB565A8 and A8 images cannot be masked at this moment.
- The mask is always center aligned on the image. Tiling and positioning can be added later.

Test and docs is still missing. First, I would like to verify if you agree with my approach on this feature.

cc @XuNeo  

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-02-01 12:43 UTC, XuNeo commented
Thank you Gabor. It looks good to me.
@bjsylvia @terry0012 @FASTSHIFT Please help to review the code.

2024-02-05 17:55 UTC, PGNetHun requested changes

2024-02-05 17:55 UTC, PGNetHun commented on docs/overview/style-props.md
> +If set a layer will be created ofr the widget and the layer will be masked with this A8 bitmap mask.
Typo: _ofr_

2024-02-05 17:55 UTC, PGNetHun commented on scripts/style_api_gen.py
> + 'dsc': "If set a layer will be created ofr the widget and the layer will be masked with this A8 bitmap mask."},
Typo: _ofr_

2024-02-05 17:55 UTC, PGNetHun commented on src/draw/sw/lv_draw_sw.c
> +                if(masked && (cf == LV_COLOR_FORMAT_A8 && cf == LV_COLOR_FORMAT_RGB565A8)) {
Typo: second `&&` operator (for color formats) should be `||`.

2024-02-06 10:59 UTC, PGNetHun submitted a review, later dismissed

2024-02-08 07:36 UTC, PGNetHun submitted a review, later dismissed

2024-02-08 07:36 UTC, PGNetHun commented on docs/overview/layer.rst
> +In LVGL "layers"" can be interpreted in various ways:
typo: double double-quotes

2024-02-08 14:10 UTC, kisvegabor commented on docs/overview/layer.rst
> +In LVGL "layers"" can be interpreted in various ways:
fixed

2024-02-08 14:43 UTC, PGNetHun approved these changes

2024-02-10 19:57 UTC, kisvegabor commented
@XuNeo I merge it now, please open an issue if feel like something is missing.

2024-02-10 19:57 UTC, merged