docs(contributing): update the feature development workflow
kisvegabor/lvgl pull request #5601
Opened 2024-02-05 15:24 UTC by kisvegabor

### Description of the feature or fix

The current shaping/pitching workflow wasn't really took off. Now I also feel like it's too complicated and not intuitive  enough. 

I think we should be good with having an issue template too where we can see all the important aspects of the larger features.  

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-02-05 17:20 UTC, PGNetHun requested changes

2024-02-05 17:20 UTC, PGNetHun commented on .github/ISSUE_TEMPLATE/feat-planning.yml
> +      placeholder: Ideally something measurable, efor example make something 20% faster/smaller/shorter/etc.
Typo: _**e**for example_ -> _for example_

2024-02-05 17:20 UTC, PGNetHun commented on docs/CONTRIBUTING.rst
> +- **Develop features**: Help to deign or develop a feature. See below.
Typo: _deign_ -> _de**s**ign_

2024-02-06 08:00 UTC, kisvegabor commented
Fixed, thanks!

2024-02-06 18:21 UTC, PGNetHun approved these changes

2024-02-07 04:15 UTC, merged