ci(assets): add LV_BUILD_TEST guard
kisvegabor/lvgl pull request #5616
Opened 2024-02-07 09:49 UTC by kisvegabor

### Description of the feature or fix

@XuNeo The images in the `test_images` folder doesn't have the guards. I think it would be uses full to add a `--guard "FOO == 3"` parameter to the image convert. What do you think?

fixes #5581

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-02-07 15:55 UTC, XuNeo commented
The script currently have `LV_BUILD_TEST` and bunch of other macros. 

The issue of global variable name conflict cannot be simply solved by adding more guard. It should be addressed to use unique name like prefixing it with `test_`, `examples_`, `demos_` etc.

2024-02-07 19:09 UTC, PGNetHun requested changes

2024-02-07 19:09 UTC, PGNetHun commented on tests/src/test_assets/test_animimg001.c
> +#if LV_BUILD_TEST && LV_USE_ANIMIMG
Rename in `#endif` line, too

2024-02-07 19:09 UTC, PGNetHun commented on tests/src/test_assets/test_kern_one_otf.c
> +#include <stdint.h>
Missing `#if LV_BUILD_TEST` line

2024-02-07 21:12 UTC, kisvegabor commented on tests/src/test_assets/test_kern_one_otf.c
> +#include <stdint.h>
Fixed

2024-02-07 21:12 UTC, kisvegabor commented on tests/src/test_assets/test_animimg001.c
> +#if LV_BUILD_TEST && LV_USE_ANIMIMG
Fixed

2024-02-07 21:17 UTC, kisvegabor commented
Thank you @PGNetHun.

@XuNeo 
> The issue of global variable name conflict cannot be simply solved by adding more guard. It should be addressed to use unique name like prefixing it with test_, examples_, demos_ etc.

I think the unique name is not enough:
- In lack of proper linker configuration the unused variables might be linked too 
- It can conflict with the user's image. Not likely, but can happen.

Besides having a `guard` option might be useful for the users too to allow easily switching between images.  We could also use it select images based on `LV_COLOR_DEPTH`.

2024-02-09 11:31 UTC, PGNetHun submitted a review, later dismissed

2024-02-12 18:36 UTC, kisvegabor commented
By passing the merge block after a trivial change.

2024-02-12 18:36 UTC, merged