feat(draw_buf): support indexed image in draw_buf_copy
kisvegabor/lvgl pull request #5686
Opened 2024-02-19 11:33 UTC by XuNeo

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-02-22 09:29 UTC, FASTSHIFT requested changes

2024-02-22 09:29 UTC, FASTSHIFT commented on src/draw/lv_draw_buf.c
> +            lv_memcpy(dest->data, src->data, LV_COLOR_INDEXED_PALETTE_SIZE(dest->header.cf) * 4);
4 -> sizeof(lv_color32_t)

2024-02-22 10:18 UTC, FASTSHIFT requested changes

2024-02-22 10:18 UTC, FASTSHIFT commented on src/draw/lv_draw_buf.c
> +    data += LV_COLOR_INDEXED_PALETTE_SIZE(buf->header.cf) * 4;
4 -> sizeof(lv_color32_t))

2024-02-22 11:49 UTC, FASTSHIFT approved these changes

2024-02-24 12:54 UTC, kisvegabor reviewed
Looks good, but could you add a test for it?

2024-02-24 13:21 UTC, XuNeo commented
Hi Gabor,

The test can be covered in https://github.com/lvgl/lvgl/pull/5690/files#diff-4cda730c9bc038547013a81b7cf252aaafe3cd9bb10e5230e6d181fbc6bd71daR89 which will check buffer copy for all supported color formats.

2024-03-03 17:56 UTC, kisvegabor commented
Awesome!

2024-03-03 17:56 UTC, kisvegabor approved these changes

2024-03-03 17:56 UTC, merged