fix(stdlib): fix issues when using LVGL TLSF memory pool to manage more than 4 GiB of memory
kisvegabor/lvgl pull request #5720
Opened 2024-02-22 11:18 UTC by MouriNaruto

### Description of the feature or fix

People will know that I'm developing UEFI applications with LVGL in recent days after read https://github.com/lvgl/lvgl/issues/5391#issuecomment-1909771955.

Because UEFI memory pool will cause many memory fragments. So, my project uses LVGL builtin TLSF memory pool to manage the memory. And I found if I use LVGL TLSF memory pool to manage more than 4 GiB of memory, I can get the correct result via  lv_mem_monitor API.

I also found the original LVGL implementation have considered about the 64-bit environments and many lv_mem APIs use size_t to manage size. So, I think it should not break the ABI for 32-bit environments if we use size_t type instead of uint32_t type to fix the issue. (For 64-bit LVGL users needs to recompile. But I think most people don't use 64-bit LVGL instance in the current stage. It should be acceptable.)

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

Kenji Mouri

2024-02-22 11:22 UTC, MouriNaruto commented
I think there are some issues should be also fixed for LVGL. (Need some time to do.)

Kenji Mouri

2024-02-22 12:53 UTC, MouriNaruto commented
It looks like all CIs are passed. It should be continued.

Kenji Mouri

2024-02-22 13:07 UTC, XuNeo submitted a review, later dismissed

2024-02-22 13:28 UTC, MouriNaruto commented
![image](https://github.com/lvgl/lvgl/assets/10867563/471db4ca-c743-4462-9bf9-22eba9d81e6e)
Here is the screenshot of just using LVGL TLSF memory pool to manage 6 GiB of memory in my test virtual machine with this fix.

Kenji Mouri

2024-02-22 13:32 UTC, FASTSHIFT requested changes

2024-02-22 13:32 UTC, FASTSHIFT commented on src/stdlib/lv_mem.c
> +                    (size_t)(mon.total_size - mon.free_size), mon.used_pct, mon.frag_pct,
remove size_t cast.

2024-02-22 13:32 UTC, FASTSHIFT commented on src/stdlib/lv_mem.c
> +                    (size_t)(mon.total_size - mon.free_size), mon.used_pct, mon.frag_pct,
remove size_t cast.

2024-02-22 13:34 UTC, MouriNaruto commented on src/stdlib/lv_mem.c
> +                    (size_t)(mon.total_size - mon.free_size), mon.used_pct, mon.frag_pct,
OK. I have modified it.

Kenji Mouri

2024-02-22 13:34 UTC, MouriNaruto commented on src/stdlib/lv_mem.c
> +                    (size_t)(mon.total_size - mon.free_size), mon.used_pct, mon.frag_pct,
OK. I have modified it.

Kenji Mouri

2024-02-22 14:47 UTC, FASTSHIFT approved these changes

2024-02-24 12:58 UTC, kisvegabor approved these changes
Awesome, thank you!

2024-02-24 13:06 UTC, merged