Add support for FreeRTOS ported by Espressif
kisvegabor/lvgl pull request #5862
Opened 2024-03-13 18:21 UTC by HanesSciarrone

### Description of the feature or fix

The FreeRTOS ported by Espressif changes the standard FreeRTOS API to support multi-core SoCs. Therefore, this change generate compatibility with the new Espressif API. 

Fixes issue #5810

2024-03-13 22:39 UTC, kisvegabor reviewed
Thank you! 

It just came to my mind that we could automatically detect the ESP environment via an `#ifdef`. E.g. `#ifdef ESP_PLATFORM` I'm not sure if really `ESP_PLATFORM` shall  be used, but we are using it in [Cmake](https://github.com/lvgl/lvgl/blob/master/CMakeLists.txt#L11C4-L11C16).

What do you think about it?

2024-03-13 22:39 UTC, kisvegabor commented on Kconfig
> +            config LV_OS_FREERTOS_ESP
Check the indentation.

2024-03-14 08:16 UTC, PGNetHun requested changes
Just minor indentation corrections are needed, the config and code changes seem OK.

2024-03-14 08:16 UTC, PGNetHun commented on Kconfig
> +            default 3 if LV_OS_FREERTOS_ESP
Use same indentation (TAB) in your new lines.

2024-03-14 08:45 UTC, XuNeo commented on src/osal/lv_freertos.c
> +#endif
How about define a macro above to handle differences between FREERTOS and FREERTOS_ESP?

```c
#if LV_USE_OS == LV_OS_FREERTOS
        #define _enter_critical() /*need better name*/ taskENTER_CRITICAL();
        #define _exit_critical()
#elif LV_USE_OS == LV_OS_FREERTOS_ESP
        #define _enter_critical() taskENTER_CRITICAL(&critSectionMux);
        #define _exit_critical()
#endif
```

2024-03-14 21:32 UTC, HanesSciarrone commented
Hi @kisvegabor 

I've done some research on the ESP_PLATFORM macro. As far as I can see the macro is set to 1 when the CMake file is processed within the ESP-IDF build system [Documentation ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#preset-component-variables). My doubt is if we use the Arduino framework instead of ESP-IDF, I'll test it in my development environment while writing in the issue to ask the users if they can test it also.

2024-03-16 03:02 UTC, HanesSciarrone commented
Hi @kisvegabor 

I've tested the approach you commented using the ESP_PLATFORM macro and it works perfectly. I think that it is a better approach because the modified files are less.

2024-03-16 06:45 UTC, kisvegabor commented
Great! Please update PR accordingly.

2024-03-16 07:12 UTC, PGNetHun approved these changes
Great, these new changes are even better!

2024-03-16 10:29 UTC, HanesSciarrone commented
@kisvegabor What do you mean by updating the PR accordingly? I already uploaded the changes when I replied to you.

2024-03-16 12:42 UTC, XuNeo approved these changes

2024-03-16 13:40 UTC, kisvegabor approved these changes
My bad, all look good! Thank you!

2024-03-16 13:41 UTC, merged