Feat/arduino littlefs driver
kisvegabor/lvgl pull request #5905
Opened 2024-03-18 20:03 UTC by PierreRambaud

### Description of the feature or fix

A driver to be able to use Arduino ESP LittleFS file system.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-03-18 20:13 UTC, PGNetHun requested changes
Thanks, only some minor (precise) wordings are needed.

2024-03-18 20:13 UTC, PGNetHun commented on Kconfig
> +			bool "File system on top of littlefs API"
To distinguish from the other littlefs driver, please add "Arduino ESP" words to description:
```suggestion
			bool "File system on top of Arduino ESP littlefs API"
```

2024-03-18 20:13 UTC, PGNetHun commented on docs/libs/fs.rst
> +- Arduino LITTLEFS (a little fail-safe filesystem designed for Arduino ESP)
```suggestion
- Arduino ESP LITTLEFS (a little fail-safe filesystem designed for Arduino ESP)
```

2024-03-18 20:13 UTC, PGNetHun commented on src/lv_conf_internal.h
> +/*API for Arduino LittleFs. */
```suggestion
/*API for Arduino ESP LittleFS. */
```

2024-03-19 07:47 UTC, PGNetHun approved these changes

2024-03-19 07:48 UTC, PGNetHun commented on src/lv_conf_internal.h
> +/*API for Arduino LittleFs. */
The comment is not corrected yet, but config name reflects that it's for Arduino ESP, so OK.

2024-03-20 12:51 UTC, kisvegabor approved these changes
Wonderful! :tada: 

Thank you! Can you tell what is the plan with the SD library?

2024-03-20 12:51 UTC, merged

2024-03-21 07:54 UTC, PierreRambaud commented
I'm gonna make it in a few days, sure it'll be ready for the next week!

2024-04-29 11:42 UTC, matixan commented
Hello guys
I'm more than little confused about using this driver. Docs are unclear to me. 
How is `lv_littlefs_set_handler(...)` supposed to work?
What header should I include to use this function, and what is an example parameter?
I want to use this driver with File explorer example for selecting configuration files.
My app is working with SDMMC Arduino library. MCU is ESP32-S3. 
I have access to files in my non GUI app, but file explorer gives me error nr 3 when `show_dir` is called, like it's not correctly initialised.

2024-04-29 13:17 UTC, PierreRambaud commented
> lv_littlefs_set_handler

The `lv_littlefs_set_handler` is related to `lfs.h` driver, not the Arduino one. For `lfs.h` you have to follow the instruction provided by the original repository: https://github.com/littlefs-project/littlefs

If you have Arduino.h installed, you can use the lvgl configuration like I did here: https://github.com/PierreRambaud/lvgl-arduino-sd-example/blob/master/lib/lv_conf/lv_conf.h#L631 and that's it, you should be able to use it like this: https://github.com/PierreRambaud/lvgl-arduino-sd-example/blob/master/src/arduino-sd.cpp#L42

2024-04-29 13:47 UTC, matixan commented
Sorry for trouble
Now i see that in master branch there are arduino related files.
I'll check them out.

2024-04-29 15:20 UTC, PierreRambaud commented
> Sorry for trouble Now i see that in master branch there are arduino related files. I'll check them out.

It will probably be easier, I had a lot of trouble playing with the original lfs.h https://github.com/PierreRambaud/pokegotchi/commit/eec197e5deb2c412d7e18e27ae00a2ab78b050e9 :sweat_smile: