Doc fixes
kisvegabor/lvgl pull request #6423
Opened 2024-06-25 19:20 UTC by ceggers-arri

### Description of the feature or fix

Documentation updates. Mainly update type and allocation of buffers for ```lv_display_set_buffers()```

2024-06-28 07:46 UTC, kisvegabor commented on docs/get-started/quick-overview.rst
> +   buf1 = lv_malloc(buf_size);
I think promoting the use of `lv_malloc` is not a good idea. Usually `LV_MEM_SIZE` is < 100kB so in most of the cases it will not work. 

To avoid using magic numbers you can do something like:
```c
#define BUF_SIZE  MY_DISP_HOR_RES * MY_DISP_VER_RES / 10 * LV_COLOR_FORMAT_GET_BPP(LV_COLOR_FORMAT_RGB565) / 8 

static uint8_t buf1[BUF_SIZE];
```

But I think this is more readable:
```c
/*Allocate a buffer for 1/10 screen size. `x2` for RGB565. Use `x3` for RGB888 or `x4` for ARGB888*/
static uin8_t buf1[MY_DISP_HOR_RES * MY_DISP_VER_RES / 10 * 2];            
```

2024-06-28 08:14 UTC, ceggers-arri commented on docs/get-started/quick-overview.rst
> +   buf1 = lv_malloc(buf_size);
I didn't know that there is a ```constexpr``` version of ```lv_color_format_get_bpp()```. I personally would also prefer staying at ```static``` allocations.

I started working with LVGL only a few days ago. For me it took much time to understand that the buffer has the type "array of LV_COLOR_FORMAT".

What about the following:
```
/* lv_color.h */
#define LV_COLOR_FORMAT_GET_SIZE(cf) (LV_COLOR_FORMAT_GET_BPP(cf) + 7 >> 3)

/* 
/*Allocate a buffer for 1/10 screen size.*/
#define BYTE_PER_PIXEL (LV_COLOR_FORMAT_GET_SIZE(LV_COLOR_FORMAT_RGB565))
static uint8_t buf1[MY_DISP_HOR_RES * MY_DISP_VER_RES / 10 * BYTE_PER_PIXEL];
```

2024-07-04 20:43 UTC, kisvegabor commented on docs/get-started/quick-overview.rst
> +   buf1 = lv_malloc(buf_size);
Sounds good to me. 

Just please add comment like below to be sure that it's perfectly clear for everyone:
```c
#define BYTE_PER_PIXEL (LV_COLOR_FORMAT_GET_SIZE(LV_COLOR_FORMAT_RGB565)) /*will be 2 for RGB565 */
```

2024-07-09 11:37 UTC, kisvegabor reviewed
Thank you for the update! I've found only  2 typos.

2024-07-09 11:37 UTC, kisvegabor commented on docs/integration/chip/stm32.rst
> +   #define BUFFF_SIZE (DISPLAY_WIDTH * 10 * BYTE_PER_PIXEL)
```suggestion
   #define BUFF_SIZE (DISPLAY_WIDTH * 10 * BYTE_PER_PIXEL)
```

2024-07-09 11:37 UTC, kisvegabor commented on docs/integration/chip/stm32.rst
> +   #define BUFFF_SIZE (DISPLAY_WIDTH * 10 * BYTE_PER_PIXEL)
```suggestion
   #define BUFF_SIZE (DISPLAY_WIDTH * 10 * BYTE_PER_PIXEL)
```

2024-07-09 11:45 UTC, ceggers-arri commented on docs/integration/chip/stm32.rst
> +   #define BUFFF_SIZE (DISPLAY_WIDTH * 10 * BYTE_PER_PIXEL)
fixed, sorry

2024-07-10 13:14 UTC, kisvegabor approved these changes, later dismissed
Thank you! :slightly_smiling_face:

2024-07-11 16:16 UTC, liamHowatt approved these changes, later dismissed

2024-07-12 12:19 UTC, XuNeo commented on docs/get-started/quick-overview.rst
> +   buf1 = lv_malloc(buf_size);
I personally think below one is more clear and easy to use.

```c
LV_DRAW_BUF_DEFINE(mybuf, MY_DISP_HOR_RES, MY_DISP_VER_RES / 10, LV_COLOR_FORMAT_RGB565);
lv_display_set_draw_buffers(disp, &mybuf, NULL);
```

2024-07-12 12:29 UTC, XuNeo requested changes
This PR should rebase and merge.

2024-07-12 12:29 UTC, XuNeo commented on docs/get-started/quick-overview.rst
>  -  Create a display.
Should `Create a display` be also moved upper?

2024-07-12 12:29 UTC, XuNeo commented on src/misc/lv_color.h
> +#define LV_COLOR_FORMAT_GET_SIZE(cf) (LV_COLOR_FORMAT_GET_BPP(cf) + 7 >> 3)
```suggestion
#define LV_COLOR_FORMAT_GET_SIZE(cf) ((LV_COLOR_FORMAT_GET_BPP(cf) + 7) >> 3)
```

2024-07-12 12:45 UTC, ceggers-arri commented on docs/get-started/quick-overview.rst
>  -  Create a display.
Shouldn't matter, does it? 

My thinking was that the tick is part of the _OS setup_, which I would do prior the _display setup_.

2024-07-12 12:48 UTC, ceggers-arri commented on src/misc/lv_color.h
> +#define LV_COLOR_FORMAT_GET_SIZE(cf) (LV_COLOR_FORMAT_GET_BPP(cf) + 7 >> 3)
Changed! Although there's no difference in the result, it's now better to read (and in sync with ```lv_color_format_get_size()```).

2024-07-12 12:48 UTC, ceggers-arri commented
> This PR should rebase and merge.

Freshly rebased.

2024-07-12 13:53 UTC, XuNeo approved these changes
Thank you! I mean that this PR should not squashed :)

2024-07-15 11:08 UTC, liamHowatt approved these changes

2024-07-15 16:41 UTC, merged

2024-07-15 16:41 UTC, kisvegabor commented
Squashed, merged, thanks! 🙂