chore(tiny_ttf): fix docstring on each API
kisvegabor/lvgl pull request #6514
Opened 2024-07-16 12:18 UTC by W-Mai

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-07-16 17:08 UTC, liamHowatt approved these changes, later dismissed
:100: thanks!

2024-07-19 20:54 UTC, XuNeo submitted a review, later dismissed

2024-07-21 13:38 UTC, PGNetHun requested changes

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified file or path with the specified line height.
Start function title with capital letter.
```suggestion
 * Create ....
```

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified file or path with the specified line height with the specified cache size.
Start function title with capital letter.

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified data pointer with the specified line height.
Start function title with capital letter.

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified data pointer with the specified line height and the specified cache size.
Start function title with capital letter.

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * destroy a font previously created with lv_tiny_ttf_create_xxxx()
Start function title with capital letter.

2024-07-21 13:38 UTC, PGNetHun commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * set the size of the font to a new font_size
Start function title with capital letter.

2024-07-26 08:17 UTC, W-Mai commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified file or path with the specified line height with the specified cache size.
Nice

2024-07-26 08:17 UTC, W-Mai commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * create a font from the specified data pointer with the specified line height and the specified cache size.
Nice

2024-07-26 08:17 UTC, W-Mai commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * destroy a font previously created with lv_tiny_ttf_create_xxxx()
Nice

2024-07-26 08:17 UTC, W-Mai commented on src/libs/tiny_ttf/lv_tiny_ttf.h
> + * set the size of the font to a new font_size
Nice

2024-07-26 09:15 UTC, XuNeo approved these changes

2024-08-05 11:35 UTC, kisvegabor approved these changes

2024-08-08 12:04 UTC, FASTSHIFT approved these changes

2024-08-12 12:49 UTC, merged