refactor(iter): use circle_buff to simplify codes
kisvegabor/lvgl pull request #6901
Opened 2024-09-20 12:48 UTC by W-Mai

- Add new `lv_circle_buff_t` data structure to easily and efficiently handle cases when using queue or ping-pong buffer and so on.
- Simplify `lv_iter_t`. Use `lv_circle_buff_t` to simplify the iter peek and next logics.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-09-26 09:35 UTC, W-Mai commented
> Isn't it a FIFO?

circle fifo I think 😁

2024-09-26 14:48 UTC, kisvegabor commented
What about calling it FIFO then? :slightly_smiling_face:

2024-09-30 08:36 UTC, W-Mai commented
> What about calling it FIFO then? 🙂

The same structure in the Nuttx OS name circle buff, but I think fifo is OK.

I think the diff from fifo is circle buff has an ability of random accessing.

What do you think?

2024-09-30 11:08 UTC, kisvegabor commented
> I think the diff from fifo is circle buff has an ability of random accessing.

That's really an important difference.  Let's keep the current name.

---

I wonder if it's really worth adding a circular buffer though. By looking in `lv_iter.c` I can't see the it's significantly shorter, but a whole new module was added. Maybe I missing where the circular buffer help that much. Could you point it out?  If it's really not a game changer I rather not add it for a single use case.

2024-09-30 12:50 UTC, W-Mai commented
It is not to make the code look more concise from the number of lines, but to make the logic clearer.

The previous iter's peek buffer requires extra memmove to move data. After using circle buff, there is no need to move data, and the structure of iter is also simpler.

In addition, if you want to add infinite scrolling components, multi-buffer management, etc. in lvgl in the future, using circle buffer is also the best choice, I think.

2024-10-02 11:02 UTC, kisvegabor commented
> In addition, if you want to add infinite scrolling components, multi-buffer management, etc. in lvgl in the future, using circle buffer is also the best choice, I think.

You have just sold it to me with the hope for infinite scrolling 😀

2024-10-02 11:02 UTC, kisvegabor approved these changes, later dismissed

2024-10-02 11:03 UTC, kisvegabor commented
Oh, just one not: please use `circle_buf` instead of `circle_buff` for consistency. We use `buf` in other names.

2024-10-02 15:00 UTC, W-Mai commented
> Oh, just one not: please use `circle_buf` instead of `circle_buff` for consistency. We use `buf` in other names.

That's ok, let me do it.

2024-10-02 17:00 UTC, W-Mai commented
Done

2024-10-09 09:50 UTC, W-Mai commented
cc @FASTSHIFT @XuNeo

2024-10-09 09:59 UTC, W-Mai commented
@kisvegabor Is there anything else that needs to be modified? 😁

2024-10-09 11:25 UTC, kisvegabor submitted a review, later dismissed
Looks good, thank you!

2024-10-09 12:18 UTC, FASTSHIFT requested changes

2024-10-09 12:18 UTC, FASTSHIFT commented on src/misc/lv_circle_buf.h
> +#ifndef LV_circle_buf_H
LV_CIRCLE_BUF_H

2024-10-09 12:18 UTC, FASTSHIFT commented on src/misc/lv_circle_buf.h
> +#include "lv_assert.h"
move to C source file include

2024-10-09 12:24 UTC, FASTSHIFT commented on src/misc/lv_circle_buf.c
> +lv_result_t lv_circle_buf_resize(lv_circle_buf_t * circle_buf, const uint32_t capacity)
Add Line Break

2024-10-09 12:31 UTC, FASTSHIFT commented on src/misc/lv_circle_buf.c
> +    if(lv_array_resize(&circle_buf->array, capacity) == false) {
LV_ASSERT_NULL(circle_buf)

2024-10-09 12:31 UTC, FASTSHIFT commented on src/misc/lv_array.h
> +void lv_array_init_from_buff(lv_array_t * array, void * buff, uint32_t capacity, uint32_t element_size);
lv_array_init_from_buf

2024-10-09 12:33 UTC, FASTSHIFT commented on src/misc/lv_circle_buf.h
> +lv_circle_buf_t * lv_circle_buf_create_from_buff(void * buff, uint32_t capacity, uint32_t element_size);
buff -> buf

2024-10-09 13:10 UTC, FASTSHIFT approved these changes

2024-10-09 13:32 UTC, XuNeo approved these changes

2024-10-09 13:33 UTC, merged