feat(demo): add an ebike demo
kisvegabor/lvgl pull request #7019
Opened 2024-10-09 20:00 UTC by kisvegabor

This demo was shown on several events by many vendors, and finally could fins some time to clean it up.

https://github.com/user-attachments/assets/28aeddbc-ab02-4620-9c57-87bf4f706d4a

https://github.com/user-attachments/assets/ce707523-7dec-4ad0-8fec-a89d319616b9

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-10-10 02:51 UTC, FASTSHIFT commented
Switch to Chinese language, it should be "简体中文", not "中国人", it should be a translation errors😂.

2024-10-10 02:53 UTC, FASTSHIFT commented on demos/ebike/assets/font_gen.py
> +cjk_chars = "語言標題月日电池今日距离天的速度时间设置蓝牙灯亮度音量最大限度光照强统计三平均高时速。中国人"
"中国人" -> "简体中文", "語言標題"->"语言标题"

2024-10-10 09:16 UTC, W-Mai requested changes
Some translation problems

2024-10-10 09:16 UTC, W-Mai commented on demos/ebike/translations/zh.yml
> +  Max. speed: 最大限度。速度
```suggestion
  Max. speed: 最大速度
```

2024-10-10 09:16 UTC, W-Mai commented on demos/ebike/translations/zh.yml
> +  Title: 標題
```suggestion
  Language: 语言
  Title: 标题
```

2024-10-10 09:16 UTC, W-Mai commented on demos/ebike/translations/lv_i18n.c
> +    {"Title", "標題"},
```suggestion
    {"Language", "语言"},
    {"Title", "标题"},
```

2024-10-10 09:16 UTC, W-Mai commented on demos/ebike/translations/lv_i18n.c
> +    {"Max. speed", "最大限度。速度"},
```suggestion
    {"Max. speed", "最大速度"},
```

2024-10-10 11:30 UTC, kisvegabor commented on demos/ebike/assets/font_gen.py
> +cjk_chars = "語言標題月日电池今日距离天的速度时间设置蓝牙灯亮度音量最大限度光照强统计三平均高时速。中国人"
It's just the list of used characters.

2024-10-10 11:30 UTC, kisvegabor commented
@W-Mai Thank you, I've fixed those :slightly_smiling_face:

2024-10-14 15:17 UTC, FASTSHIFT approved these changes

2024-10-14 15:22 UTC, XuNeo approved these changes

2024-10-14 15:50 UTC, W-Mai approved these changes

2024-10-14 16:47 UTC, merged