Update LV_OBJ_FLAG_OVERFLOW_VISIBLE usage in obj.rst for v9
kisvegabor/lvgl pull request #7101
Opened 2024-10-17 18:00 UTC by stachurr

Update usage of LV_OBJ_FLAG_OVERFLOW_VISIBLE which now requires a calculation during an extended draw callback event. See https://github.com/lvgl/lvgl/issues/7091 for details.

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-10-18 03:04 UTC, FASTSHIFT submitted a review, later dismissed

2024-10-21 09:37 UTC, kissa96 approved these changes
lgtm

2024-10-22 16:16 UTC, XuNeo submitted a review, later dismissed
Thank you!

2024-10-22 16:17 UTC, XuNeo commented
@kisvegabor Please review if the doc is correct. I'm not sure of `*cur_size = LV_MAX(*cur_size, LV_HOR_RES);`

2024-10-23 06:00 UTC, kisvegabor requested changes
`LV_HOR_RES` is overkill in most of the cases and the user should be more explicit.

2024-10-23 06:00 UTC, kisvegabor commented on docs/overview/obj.rst
> +        *cur_size = LV_MAX(*cur_size, LV_HOR_RES);
lv_event_set_ext_draw_size(e, 30); /*Set 30px extra draw area around the widget*/

2024-10-23 14:39 UTC, stachurr commented
Should `LV_HOR_RES` be replaced with a user defined `ext_width`?
BTW this was taken directly from [here](https://github.com/lvgl/lvgl/issues/7091#issuecomment-2417589948).

2024-10-23 18:03 UTC, stachurr commented
How's this?

2024-10-25 20:34 UTC, kisvegabor submitted a review, later dismissed
Looks good, thank you!

2024-10-26 03:13 UTC, XuNeo commented
@stachurr Please fix the merge conflict.

2024-11-04 11:12 UTC, liamHowatt commented on docs/overview/obj.rst
> +        lv_coord_t * cur_size = lv_event_get_param(e);
```suggestion
        int32_t * cur_size = lv_event_get_param(e);
```

`lv_coord_t` is a v8 type. Still supported in the API map but `int32_t` is the convention in v9.

2024-11-04 11:12 UTC, liamHowatt commented on docs/overview/obj.rst
> +the following event callback (this was not required in previous versions).
Please also mention the specific event code `LV_EVENT_REFR_EXT_DRAW_SIZE`.

2024-11-06 17:58 UTC, stachurr commented
I'll be completely honest with you... I can't figure out how to make this merge for the life of me. I've tried cloning and merging but I either end up with a detached HEAD state or seeing no conflicts.

2024-11-07 09:44 UTC, liamHowatt commented
Can you try

```
git merge --abort
git checkout patch-1
git fetch origin
git merge origin/master
```

Search for files with "<<<<<" and resolve the conflicts and finally

```
git add .
git merge --continue
git push
```

2024-11-07 21:44 UTC, stachurr commented
After `git merge origin/master`, I get "Already up to date."... Same result if I try the other way around.

2024-11-08 09:52 UTC, liamHowatt commented
The problem was that `obj.rst` got moved to a different directory in `master`. This is a pretty hard type merge conflict to fix. It won't usually be this hard. I rebased your changes on the new file location. Please

```
git checkout patch-1
git fetch stachurr
git reset --hard stachurr/patch-1
```

To get the rebase changes.

2024-11-08 18:02 UTC, stachurr commented
Thanks for the validation lol... Is there anything else I need to do? Or have the changes been successfully merged with master?

2024-11-11 01:40 UTC, XuNeo approved these changes, later dismissed
Thank you. That looks good to me.

2024-11-11 10:49 UTC, kisvegabor requested changes

2024-11-11 10:49 UTC, kisvegabor commented on docs/details/base-widget/obj.rst
> +        *cur_size = LV_MAX(*cur_size, ext_width);
Please use the dedicated API function as suggested [here](https://github.com/lvgl/lvgl/pull/7101#discussion_r1811927930).

2024-11-12 11:00 UTC, liamHowatt commented
I didn't apply any suggested feedback. I just rebased your changes. I left it up to you to interpret the feedback.

2024-11-27 07:44 UTC, kisvegabor commented on docs/details/base-widget/obj.rst
> +        *cur_size = LV_MAX(*cur_size, ext_width);
I've applied it.

2024-11-27 07:44 UTC, kisvegabor approved these changes

2024-11-27 10:14 UTC, XuNeo approved these changes

2024-11-27 10:14 UTC, merged