refactor(draw): extract function to improve readability
kisvegabor/lvgl pull request #7229
Opened 2024-11-05 14:34 UTC by cristian-stoica

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- [x] Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-11-06 13:25 UTC, PGNetHun approved these changes

2024-11-07 12:05 UTC, kisvegabor approved these changes, later dismissed

2024-11-07 12:05 UTC, kisvegabor commented on src/draw/lv_draw.c
> +void lv_cleanup_task(lv_draw_task_t * t, lv_display_t * disp)
Can it be `static`?

2024-11-07 12:38 UTC, PGNetHun requested changes

2024-11-07 12:38 UTC, PGNetHun commented on src/draw/lv_draw.c
> +void lv_cleanup_task(lv_draw_task_t * t, lv_display_t * disp)
Good catch, I did not notice that.
Yep, it should be `static`, do not expose function to other parts of code.

2024-11-08 06:44 UTC, PGNetHun approved these changes, later dismissed

2024-11-09 05:32 UTC, kisvegabor commented on src/draw/lv_draw.c
> + *  STATIC FUNCTIONS
Please use the `STATIC FUNCTIONS` section at the bottom of the file.

2024-11-13 09:21 UTC, kisvegabor approved these changes
Looks good, thank you!

2024-11-13 09:44 UTC, PGNetHun approved these changes

2024-11-14 19:40 UTC, merged