Fix drawing of partial frame buffers on transparent displays
kisvegabor/lvgl pull request #7269
Opened 2024-11-09 20:16 UTC by Finomnis

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-11-12 09:13 UTC, liamHowatt approved these changes, later dismissed
Amazing, thank you!

To reproduce the issue on SDL, apply this diff and call `lv_example_label_5`.

```diff
diff --git a/examples/widgets/label/lv_example_label_5.c b/examples/widgets/label/lv_example_label_5.c
index 1cf988943..d4395d533 100644
--- a/examples/widgets/label/lv_example_label_5.c
+++ b/examples/widgets/label/lv_example_label_5.c
@@ -19,6 +19,8 @@ void lv_example_label_5(void)
     lv_style_init(&label_style);
     lv_style_set_anim(&label_style, &animation_template);
 
+    lv_obj_set_style_bg_opa(lv_screen_active(), 8, 0);
+
     lv_obj_t * label1 = lv_label_create(lv_screen_active());
     lv_label_set_long_mode(label1, LV_LABEL_LONG_SCROLL_CIRCULAR);      /*Circular scroll*/
     lv_obj_set_width(label1, 150);
diff --git a/src/drivers/sdl/lv_sdl_window.c b/src/drivers/sdl/lv_sdl_window.c
index 30b84f495..591371479 100644
--- a/src/drivers/sdl/lv_sdl_window.c
+++ b/src/drivers/sdl/lv_sdl_window.c
@@ -101,6 +101,7 @@ lv_display_t * lv_sdl_window_create(int32_t hor_res, int32_t ver_res)
         lv_free(dsc);
         return NULL;
     }
+    lv_display_set_color_format(disp, LV_COLOR_FORMAT_ARGB8888);
     lv_display_add_event_cb(disp, release_disp_cb, LV_EVENT_DELETE, disp);
     lv_display_set_driver_data(disp, dsc);
     window_create(disp);
```

2024-11-12 10:26 UTC, Finomnis commented
> Amazing, thank you!
> 
> To reproduce the issue on SDL, use partial mode and call:
> 
> ```c
> lv_display_set_color_format(NULL, LV_COLOR_FORMAT_ARGB8888);
> lv_obj_set_style_bg_opa(lv_screen_active(), 8, 0);
> lv_example_label_5();
> ```

@liamHowatt

Awesome, thanks :)
In case you want to add a test for it, I'm unfamiliar with the lvgl test framework.

2024-11-13 03:51 UTC, FASTSHIFT requested changes

2024-11-13 03:51 UTC, FASTSHIFT commented on src/core/lv_refr.c
> +        lv_area_set(&clear_area, layer->_clip_area.x1, layer->_clip_area.y1,
lv_area_t clear_area = layer->_clip_area;

2024-11-13 08:33 UTC, kisvegabor approved these changes
A customer just reported this issue, but I couldn't reproduce it. Now I know why: I was using DIRECT rendering (the buffer is always at 0;0) and they were using PARTIAL.

So thank you very much! ❤️

2024-11-13 08:33 UTC, kisvegabor commented
@liamHowatt @FASTSHIFT please review.

2024-11-13 11:43 UTC, FASTSHIFT approved these changes

2024-11-14 19:39 UTC, merged