docs: chinese translation link only on the homepage
kisvegabor/lvgl pull request #7370
Opened 2024-11-29 07:53 UTC by 100ask

CC @kisvegabor @PGNetHun @vwheeler63 

https://github.com/lvgl/lvgl/issues/7297

2024-11-29 14:21 UTC, vwheeler63 requested changes
This will get the directory separator appropriate to the platform it is running on.

2024-11-29 14:21 UTC, vwheeler63 commented on docs/add_translation.py
> +    rst_file = temp_directory + "/index.rst"
```suggestion
    rst_file = os.path.join(temp_directory, 'index.rst')
```

2024-11-30 13:35 UTC, vwheeler63 approved these changes
Verified that this accomplishes the objective of limiting the translation links to only the landing page.

2024-12-02 02:57 UTC, FASTSHIFT approved these changes

2024-12-03 12:07 UTC, liamHowatt approved these changes

2024-12-03 12:07 UTC, merged