docs(label): add documentation and example for text recoloring
kisvegabor/lvgl pull request #7460
Opened 2024-12-16 05:47 UTC by lhdjply

docs(label): add documentation and example for text recoloring

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-12-19 01:01 UTC, C47D approved these changes

2024-12-19 23:40 UTC, liamHowatt reviewed
Nice!

2024-12-19 23:40 UTC, liamHowatt commented on docs/details/widgets/label.rst
> +see example ``Line wrap, recoloring and scrolling``.
```suggestion
function. Recoloring is only supported when the text is wrapped with 
``#ff0000 ... #`` syntax is in one line. It is not supported in wrapped text. 
See example ``Line wrap, recoloring and scrolling``.
```

2024-12-19 23:42 UTC, liamHowatt commented
cc @vwheeler63

2024-12-20 04:08 UTC, lhdjply commented on docs/details/widgets/label.rst
> +see example ``Line wrap, recoloring and scrolling``.
Thank you!

2024-12-20 12:57 UTC, liamHowatt submitted a review, later dismissed

2024-12-20 14:20 UTC, vwheeler63 requested changes
Nice!

2024-12-20 14:20 UTC, vwheeler63 commented on docs/details/widgets/label.rst
> +See example ``Line wrap, recoloring and scrolling``.
```suggestion
function. In the context of word-wrapped text, any Recoloring started on a
line will be terminated at the end of the line where the line is wrapped if it
was not already terminated by an ending ``#`` in the text.
```

2024-12-20 15:10 UTC, liamHowatt approved these changes

2024-12-20 15:11 UTC, liamHowatt commented on docs/details/widgets/label.rst
> +See example ``Line wrap, recoloring and scrolling``.
Thanks Vic!

2024-12-22 19:25 UTC, kisvegabor approved these changes
Thank you!

2024-12-22 19:26 UTC, merged