feat(draw): add lv_draw_letter support
kisvegabor/lvgl pull request #7490
Opened 2024-12-20 06:40 UTC by W-Mai

support rotation/colorful and so on.

we can make some interesting effects like:

![letter_0](https://github.com/user-attachments/assets/dbf96fb7-0f99-47b9-9862-93def0fcc1c3)

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2024-12-20 06:44 UTC, FASTSHIFT requested changes

2024-12-20 06:44 UTC, FASTSHIFT commented on src/draw/vg_lite/lv_draw_vg_lite_label.c
> +#if LV_USE_VG_LITE_THORVG
move to `lv_vg_lite_path.h` and use name `LV_VG_LITE_PATH_COORD_MIN/MAX`

2024-12-20 11:40 UTC, W-Mai commented
this fix some problem when draw buf create return with a same address rarely
- #7494

2024-12-20 21:34 UTC, kisvegabor commented
Amazing! :tada: :heart: 
It perfectly prepares the ground for an API to write text on a path. With @XuNeo we were talking about it [here](https://github.com/lvgl/lvgl/issues/4855). 

I'm not sure about the curved text API, but maybe our vector path API can be reused (i.e. describe the path with arcs, beziers and lines). After that we need a way to get the x,y points of the curve after each letter width distance. Anyway, we don't need to resolve it now, just wanted to tell it in my excitement. 😄

2024-12-21 07:41 UTC, W-Mai commented
> Amazing! 🎉 ❤️ It perfectly prepares the ground for an API to write text on a path. With @XuNeo we were talking about it [here](https://github.com/lvgl/lvgl/issues/4855).
> 
> I'm not sure about the curved text API, but maybe our vector path API can be reused (i.e. describe the path with arcs, beziers and lines). After that we need a way to get the x,y points of the curve after each letter width distance. Anyway, we don't need to resolve it now, just wanted to tell it in my excitement. 😄

事实上，这个事情也是我一直很想做的。

我之前是这样计划的，之前我提交了一个 lv_iter_t 的组件，通过 lv_iter_t 基于 path 创建一个 可迭代对象，可以选择是按照距离往后迭代还是按照迭代步数往后迭代。我称之为 lv_path_gen_t，然后通过每一次的 lv_iter_next() 方法可以方便的获取到 每一个点的 x，y 和 rotation（法线斜率等等）。

之前我还做了一个 曲线文本模拟器，你可以看看： 

In fact, this is what I have always wanted to do. 😃

I planned it like this before. Previously, I submitted a component of `lv_iter_t`, we can  create an iterable object based on path through `lv_iter_t`. You can choose whether to iterate forward according to the `distance` or iterate forward according to the number of iteration `steps`. I call it `lv_path_gen_t`, and then through each `lv_iter_next()` method, you can conveniently obtain the `x`, `y` and `rotation` (famal slope, etc.) of each point (step).

I also made a curve text simulator before. You can take a look:

<img width="1707" alt="image" src="https://github.com/user-attachments/assets/4972cbb3-77d8-48aa-9f40-954ab2283bb9" />


https://w-mai.github.io/curved_label_egui/

2024-12-21 07:47 UTC, W-Mai commented
Now this PR is blocked by 
- #7494

2024-12-24 10:05 UTC, W-Mai commented
32 bits and 64 bits have diff colors 🥲

https://github.com/lvgl/lvgl/actions/runs/12479900599/job/34829811589?pr=7490#step:7:5039

2025-01-03 21:16 UTC, kisvegabor commented
You can use this workaround:

https://github.com/lvgl/lvgl/blob/e4aac4c67a6c440ba4bec0c587aebd33b068222d/tests/src/test_cases/draw/test_draw_vector.c#L256-L264

2025-01-04 16:04 UTC, W-Mai commented
> You can use this workaround:
> 
> https://github.com/lvgl/lvgl/blob/e4aac4c67a6c440ba4bec0c587aebd33b068222d/tests/src/test_cases/draw/test_draw_vector.c#L256-L264

Sure, I had solved this problem via this way. 😁

2025-01-06 02:59 UTC, FASTSHIFT approved these changes, later dismissed

2025-01-06 09:48 UTC, W-Mai commented
@kisvegabor Is there anything else that's a problem? If there's not too much of a problem, we can iterate slowly 😁

2025-01-07 11:52 UTC, kisvegabor submitted a review, later dismissed

2025-01-07 11:53 UTC, kisvegabor commented
Sure! It looks good in general. 

As we have discussed above the next step should be to add some kind of path support.

2025-01-07 11:55 UTC, kisvegabor commented
Oh just one thing. Please add an example too. (Can be similar to the tests)

2025-01-08 13:18 UTC, W-Mai commented
> Sure! It looks good in general.
> 
> As we have discussed above the next step should be to add some kind of "text path" style property support.

Sure! I'm working on it. 😁

> Oh just one thing. Please add an example too. (Can be similar to the tests)

Ok, let me add it.

2025-01-09 12:03 UTC, W-Mai commented
@kisvegabor how about this 😁


https://github.com/user-attachments/assets/1dd0114a-615a-4ce7-a2a0-6cbffdfc0bed

2025-01-09 12:35 UTC, W-Mai commented
Another one

https://github.com/user-attachments/assets/19ed8143-ed2d-45c6-88e1-f2f0bb8c94f2

2025-01-13 08:54 UTC, kisvegabor commented
I love i! :heart: 

FYI: [LinkedIn post](https://www.linkedin.com/posts/lvglgui_lvgl-activity-7284492681500659712-9-N6?utm_source=share&utm_medium=member_desktop)

2025-01-13 08:55 UTC, kisvegabor submitted a review, later dismissed

2025-01-13 08:55 UTC, kisvegabor commented on examples/widgets/canvas/index.rst
> +----------------
```suggestion
Draw Fancy Letter Effects
--------------------------
```

2025-01-13 08:55 UTC, kisvegabor commented on examples/widgets/canvas/index.rst
> +----------------
```suggestion
Draw Fancy Letter Effects 2
---------------------------
```

2025-01-15 06:18 UTC, kisvegabor approved these changes

2025-01-16 02:42 UTC, FASTSHIFT approved these changes

2025-01-16 02:42 UTC, merged