feat(draw/sw) Allow custom handlers
kisvegabor/lvgl pull request #7531
Opened 2024-12-31 09:50 UTC by faxe1008

This allows LVGL users to register custom software draw handlers. It is beneficial to be able to add blending support for more unusual color formats that are unlikely to be included in the upstream repository (e.g., e-Ink displays with 7-indexed color formats).
It also allows users to register custom handlers if the behavior of the existing ones regarding performance or rules (e.g., for I1, when is a pixel considered to be on?) does not meet their needs.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

2025-01-02 21:31 UTC, uLipe requested changes
I like the idea, the only point that I concerns me is about the configuration name, so instead of : `LV_DRAW_SW_CUSTOM_HANDLERS` , why not something like: `LV_DRAW_SW_CUSTOM_BLEND_HANDLERS` ?

I understand the name is large , but the first option imply you are enabling an option that allows to register any kind of custom handlers, since in the reality you are just enabling a feature that allows to override the blend handler. 

Other than that, nice work!

2025-01-03 07:21 UTC, faxe1008 commented
True, the name you suggested is better. Adjusted accordingly :^)

2025-01-03 21:45 UTC, kisvegabor commented
What a coincidence! https://github.com/lvgl/lvgl/pull/7509 aims to solve the same issue. This PR is more flexible as it allows registering multiple handlers at runtime, but the solution in https://github.com/lvgl/lvgl/pull/7509 is much simpler. 

cc @MarkIoanAmat

2025-01-28 10:24 UTC, kisvegabor commented
Not stale, let's keep it going. Sorry for my absence.

2025-02-06 12:25 UTC, kisvegabor commented
I was talking with @MarkIoanAmat about this topic and we concluded that your version should be used with a little modification. 
Instead of adding new `blend_color` and `blend_image` functions the whole `lv_draw_sw_blend`. It is because [this part](https://github.com/lvgl/lvgl/blob/master/src/draw/sw/blend/lv_draw_sw_blend.c#L83-L85) can be used only with standard color formats. E.g. it won't know how to go to x=10, y=22 on an indexed 3 bit colored frame buffer. However, if call the user's function at the very beginning the user can de any magic with exotic color formats. 

Do you agree with this direction? If you are you interested in updating the PR accoridngly?

2025-02-14 08:57 UTC, kisvegabor commented
I've checked our schedule , however we very busy with the preparation to Embedded World @liamHowatt can work on in only at the beginning of March. If someone is interested in picking it up, it'd be more than welcome

2025-02-14 09:24 UTC, faxe1008 commented
Quite busy as well but I will see if i can manage something in next two weeks :^)

2025-02-19 09:03 UTC, faxe1008 commented
@kisvegabor pushed a change with your suggested changes :^)

2025-02-21 18:48 UTC, kisvegabor reviewed
Thank you Fabian! I'm really thankful! 

It looks good to me, just one minor suggestion. 

cc @MarkIoanAmat

2025-02-21 18:48 UTC, kisvegabor commented on src/draw/sw/lv_draw_sw.c
> +lv_draw_sw_blend_handler_t lv_draw_sw_get_blend_handler(lv_color_format_t cf)
```suggestion
lv_draw_sw_blend_handler_t lv_draw_sw_get_blend_handler(lv_color_format_t dest_cf)
```

2025-02-24 14:31 UTC, faxe1008 commented on src/draw/sw/lv_draw_sw.c
> +lv_draw_sw_blend_handler_t lv_draw_sw_get_blend_handler(lv_color_format_t cf)
Done :^)

2025-02-24 18:54 UTC, kisvegabor reviewed
Sorry, just a last one.

2025-02-24 18:54 UTC, kisvegabor commented on lv_conf_template.h
> +    #define LV_DRAW_SW_CUSTOM_BLEND_HANDLERS  0
IMO this config is not required as enabling this feature by default doesn't make a big difference.

2025-02-25 15:52 UTC, faxe1008 commented on lv_conf_template.h
> +    #define LV_DRAW_SW_CUSTOM_BLEND_HANDLERS  0
I added it as a config because imo. especially when working on resource constraint devices you should only pay for what you use (flash/ram). Maybe its kind of zephyr-ish in it's approach but I feel like generally the lower the footprint, the better. On the flip side this makes testing more difficult of course, if every feature has its own toggle :^)

2025-02-25 21:47 UTC, kisvegabor commented on lv_conf_template.h
> +    #define LV_DRAW_SW_CUSTOM_BLEND_HANDLERS  0
Yeah, it's really a trade off. On the flip side (besides the more complex testing) I also see the issue of more config options. In this case the extra memory usage is only a few bytes which is less of an issue compared to the testing and config complexity increase. 

So unless there is a principal objection, please remove this config.

2025-02-28 17:53 UTC, kisvegabor approved these changes
Looks good, thank you!

2025-02-28 22:24 UTC, uLipe approved these changes

2025-02-28 22:24 UTC, merged