Added tab button position left or right.
kisvegabor/lvgl pull request #897
Opened 2019-02-25 14:33 UTC by zavovi

Issue #808

2019-02-25 15:14 UTC, embeddedt requested changes

2019-02-25 15:14 UTC, embeddedt commented on lv_objx/lv_tabview.c
> +    	if(ext->btns_pos <= LV_TABVIEW_BTNS_POS_BOTTOM)
Again, I think an explicit `btns_pos == LV_TABVIEW_BTNS_POS_BOTTOM || btns_pos == LV_TABVIEW_BTNS_POS_TOP` would be better. It's easier to read and understand.

2019-03-13 21:35 UTC, zavovi commented
Hello, there is more mistakes and I am working on it now. It takes more time... I am sorry about it.

2019-03-14 00:38 UTC, embeddedt commented
@zavovi No problem. Let us know when it's ready!

2019-04-11 01:00 UTC, closed without merging